<a href="https://colab.research.google.com/github/nvisagan/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module4-makefeatures/LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [4]:
# Get the Lending Club Data
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-08-08 20:58:46--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [              <=>   ]  21.56M   909KB/s    in 25s

2019-08-08 20:59:12 (868 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22606280]

In [5]:
# Unzip the zipped csv
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [6]:
import pandas as pd

# Display Options in Pandas
pd.set_option('display.max.rows', 500)
pd.set_option('display.max.columns', 500)

#Read CSV with Pandas Libraries
df = pd.read_csv('LoanStats_2018Q4.csv', header = 1, skipfooter=2, engine='python')
print(df.shape)
df.head()

(128412, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8540.01,8540.01,1936.77,1936.77,1459.99,476.78,0.0,0.0,0.0,Jul-2019,324.23,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3510.60,3510.60,926.28,926.28,489.40,436.88,0.0,0.0,0.0,Jul-2019,155.68,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (16-30 days),n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21597.84,21597.84,3686.64,3686.64,1402.16,2284.48,0.0,0.0,0.0,Jul-2019,620.81,Jul-2019,Jul-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,7021.26,7021.26,1852.50,1852.50,978.74,873.76,0.0,0.0,0.0,Jul-2019,311.35,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Sum of Missing Values in columns

df.isnull().sum().sort_values(ascending=False)

id                                            128412
member_id                                     128412
url                                           128412
desc                                          128412
hardship_dpd                                  128409
deferral_term                                 128409
hardship_amount                               128409
hardship_start_date                           128409
hardship_end_date                             128409
payment_plan_start_date                       128409
hardship_length                               128409
orig_projected_additional_accrued_interest    128409
hardship_loan_status                          128409
hardship_reason                               128409
hardship_payoff_balance_amount                128409
hardship_last_payment_amount                  128409
hardship_type                                 128409
hardship_status                               128409
settlement_percentage                         128350
settlement_term                               128350
settlement_status                             128350
settlement_amount                             128350
settlement_date                               128350
debt_settlement_flag_date                     128350
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
annual_inc_joint                              111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
mths_since_recent_inq                          16047
next_pymnt_d                                   12564
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
int_rate                                           0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
purpose                                            0
total_rec_int                                      0
total_acc                                          0
funded_amnt_inv                                    0
funded_amnt                                        0
total_rec_late_fee                                 0
recoveries                                         0
loan_amnt                                          0
collection_recovery_fee                            0
term                                               0
revol_bal                                          0
installment                                        0
pymnt_plan                                         0
loan_status                                        0
title                                              0
zip_code                                           0
addr_state                                         0
issue_d                                            0
delinq_2yrs                                        0
earliest_cr_line                                   0
verification_status                                0
annual_inc                                         0
inq_last_6mths                                     0
home_ownership                                     0
sub_grade                                          0
grade                                              0
open_acc                                           0
pub_rec                                            0
debt_settlement_flag                               0
open_il_12m                                        0
last_pymnt_amnt                                    0
num_sats                                           0
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_tl_30dpd                                       0
collections_12_mths_ex_med                         0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_old_rev_tl_op                               0
policy_code                                        0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
hardship_flag                                      0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
inq_fi                                             0
dtype: int64

In [0]:
# Drop the unneeded columns

df = df.drop(columns=['id', 'member_id', 'desc', 'url'], axis='columns')

In [16]:
# Check type of term column

type(df['term'])
df['term']

0         36
1         36
2         36
3         60
4         36
5         60
6         36
7         36
8         60
9         60
10        60
11        60
12        60
13        60
14        36
15        36
16        36
17        60
18        36
19        36
20        60
21        60
22        36
23        60
24        60
25        36
26        36
27        36
28        36
29        60
30        60
31        36
32        36
33        36
34        36
35        36
36        60
37        36
38        36
39        36
40        60
41        60
42        36
43        36
44        60
45        36
46        60
47        36
48        36
49        60
50        36
51        60
52        60
53        36
54        60
55        36
56        60
57        36
58        60
59        36
60        36
61        36
62        36
63        60
64        60
65        60
66        36
67        60
68        36
69        36
70        36
71        36
72        36
73        36
74        36
75        60
76        36
77        60
78        60
79        60
80        36
81        36
82        36
83        36
84        36
85        36
86        60
87        36
88        60
89        60
90        60
91        36
92        36
93        60
94        36
95        36
96        36
97        36
98        36
99        36
100       36
101       36
102       60
103       36
104       36
105       60
106       36
107       36
108       36
109       60
110       36
111       60
112       36
113       36
114       60
115       36
116       36
117       36
118       60
119       36
120       60
121       36
122       60
123       60
124       60
125       60
126       36
127       60
128       60
129       36
130       60
131       36
132       60
133       36
134       60
135       60
136       36
137       36
138       36
139       60
140       36
141       36
142       36
143       60
144       60
145       36
146       60
147       36
148       36
149       36
150       36
151       36
152       60
153       36
154       60
155       36
156       36
157       36
158       36
159       36
160       60
161       36
162       36
163       60
164       36
165       36
166       36
167       60
168       36
169       36
170       60
171       36
172       60
173       36
174       60
175       36
176       36
177       36
178       36
179       36
180       36
181       36
182       36
183       36
184       60
185       36
186       36
187       36
188       36
189       60
190       60
191       36
192       36
193       60
194       60
195       36
196       36
197       36
198       36
199       36
200       60
201       36
202       36
203       60
204       60
205       36
206       36
207       36
208       36
209       36
210       36
211       36
212       36
213       60
214       60
215       36
216       36
217       36
218       60
219       60
220       36
221       60
222       60
223       60
224       36
225       36
226       36
227       36
228       60
229       36
230       36
231       60
232       36
233       36
234       36
235       36
236       36
237       36
238       36
239       36
240       60
241       36
242       36
243       36
244       36
245       36
246       36
247       36
248       36
249       60
          ..
128162    36
128163    36
128164    60
128165    36
128166    36
128167    36
128168    36
128169    36
128170    36
128171    36
128172    36
128173    36
128174    36
128175    36
128176    36
128177    36
128178    36
128179    60
128180    36
128181    36
128182    60
128183    36
128184    36
128185    36
128186    36
128187    60
128188    60
128189    60
128190    60
128191    36
128192    60
128193    60
128194    36
128195    36
128196    36
128197    36
128198    36
128199    36
128200    36
128201    36
128202    36
128203    36
128204    36
128205    60
128206    36
128207    36
128208    36
128209    36
128210    36
128211    60
128212    36
128213    60
128214    36
128215    36
128216    60
128217    36
128218    36
128219    36
128220    60
128221    36
128222    60
128223    36
128224    60
128225    36
128226    36
128227    36
128228    36
128229    36
128230    36
128231    36
128232    36
128233    36
128234    36
128235    36
128236    36
128237    36
128238    36
128239    36
128240    36
128241    36
128242    60
128243    36
128244    36
128245    36
128246    36
128247    36
128248    60
128249    60
128250    36
128251    36
128252    60
128253    36
128254    36
128255    60
128256    36
128257    36
128258    36
128259    36
128260    36
128261    36
128262    36
128263    60
128264    36
128265    36
128266    36
128267    36
128268    60
128269    36
128270    36
128271    36
128272    36
128273    60
128274    36
128275    36
128276    36
128277    60
128278    36
128279    36
128280    36
128281    36
128282    36
128283    36
128284    36
128285    36
128286    36
128287    36
128288    36
128289    60
128290    36
128291    36
128292    36
128293    36
128294    36
128295    36
128296    36
128297    36
128298    36
128299    60
128300    36
128301    36
128302    60
128303    36
128304    36
128305    36
128306    60
128307    36
128308    36
128309    36
128310    36
128311    60
128312    36
128313    60
128314    36
128315    36
128316    36
128317    60
128318    36
128319    60
128320    60
128321    36
128322    36
128323    60
128324    60
128325    36
128326    36
128327    36
128328    36
128329    36
128330    60
128331    60
128332    36
128333    36
128334    36
128335    36
128336    36
128337    60
128338    36
128339    36
128340    36
128341    60
128342    36
128343    60
128344    36
128345    60
128346    36
128347    60
128348    36
128349    36
128350    36
128351    60
128352    36
128353    36
128354    36
128355    36
128356    36
128357    36
128358    36
128359    36
128360    60
128361    36
128362    60
128363    36
128364    36
128365    36
128366    36
128367    36
128368    36
128369    36
128370    36
128371    60
128372    36
128373    60
128374    60
128375    36
128376    36
128377    36
128378    60
128379    60
128380    60
128381    36
128382    60
128383    36
128384    36
128385    36
128386    36
128387    60
128388    36
128389    36
128390    36
128391    36
128392    36
128393    36
128394    36
128395    36
128396    60
128397    60
128398    60
128399    36
128400    60
128401    36
128402    60
128403    36
128404    60
128405    36
128406    36
128407    36
128408    36
128409    36
128410    36
128411    36
Name: term, Length: 128412, dtype: int64

In [0]:
# Create a stripping function 

def remove_month_to_int(string):
  return int(string.strip(' months'))

In [0]:
#Apply to term
df['term']= df['term'].apply(remove_month_to_int)

In [17]:
df['term']

0         36
1         36
2         36
3         60
4         36
5         60
6         36
7         36
8         60
9         60
10        60
11        60
12        60
13        60
14        36
15        36
16        36
17        60
18        36
19        36
20        60
21        60
22        36
23        60
24        60
25        36
26        36
27        36
28        36
29        60
30        60
31        36
32        36
33        36
34        36
35        36
36        60
37        36
38        36
39        36
40        60
41        60
42        36
43        36
44        60
45        36
46        60
47        36
48        36
49        60
50        36
51        60
52        60
53        36
54        60
55        36
56        60
57        36
58        60
59        36
60        36
61        36
62        36
63        60
64        60
65        60
66        36
67        60
68        36
69        36
70        36
71        36
72        36
73        36
74        36
75        60
76        36
77        60
78        60
79        60
80        36
81        36
82        36
83        36
84        36
85        36
86        60
87        36
88        60
89        60
90        60
91        36
92        36
93        60
94        36
95        36
96        36
97        36
98        36
99        36
100       36
101       36
102       60
103       36
104       36
105       60
106       36
107       36
108       36
109       60
110       36
111       60
112       36
113       36
114       60
115       36
116       36
117       36
118       60
119       36
120       60
121       36
122       60
123       60
124       60
125       60
126       36
127       60
128       60
129       36
130       60
131       36
132       60
133       36
134       60
135       60
136       36
137       36
138       36
139       60
140       36
141       36
142       36
143       60
144       60
145       36
146       60
147       36
148       36
149       36
150       36
151       36
152       60
153       36
154       60
155       36
156       36
157       36
158       36
159       36
160       60
161       36
162       36
163       60
164       36
165       36
166       36
167       60
168       36
169       36
170       60
171       36
172       60
173       36
174       60
175       36
176       36
177       36
178       36
179       36
180       36
181       36
182       36
183       36
184       60
185       36
186       36
187       36
188       36
189       60
190       60
191       36
192       36
193       60
194       60
195       36
196       36
197       36
198       36
199       36
200       60
201       36
202       36
203       60
204       60
205       36
206       36
207       36
208       36
209       36
210       36
211       36
212       36
213       60
214       60
215       36
216       36
217       36
218       60
219       60
220       36
221       60
222       60
223       60
224       36
225       36
226       36
227       36
228       60
229       36
230       36
231       60
232       36
233       36
234       36
235       36
236       36
237       36
238       36
239       36
240       60
241       36
242       36
243       36
244       36
245       36
246       36
247       36
248       36
249       60
          ..
128162    36
128163    36
128164    60
128165    36
128166    36
128167    36
128168    36
128169    36
128170    36
128171    36
128172    36
128173    36
128174    36
128175    36
128176    36
128177    36
128178    36
128179    60
128180    36
128181    36
128182    60
128183    36
128184    36
128185    36
128186    36
128187    60
128188    60
128189    60
128190    60
128191    36
128192    60
128193    60
128194    36
128195    36
128196    36
128197    36
128198    36
128199    36
128200    36
128201    36
128202    36
128203    36
128204    36
128205    60
128206    36
128207    36
128208    36
128209    36
128210    36
128211    60
128212    36
128213    60
128214    36
128215    36
128216    60
128217    36
128218    36
128219    36
128220    60
128221    36
128222    60
128223    36
128224    60
128225    36
128226    36
128227    36
128228    36
128229    36
128230    36
128231    36
128232    36
128233    36
128234    36
128235    36
128236    36
128237    36
128238    36
128239    36
128240    36
128241    36
128242    60
128243    36
128244    36
128245    36
128246    36
128247    36
128248    60
128249    60
128250    36
128251    36
128252    60
128253    36
128254    36
128255    60
128256    36
128257    36
128258    36
128259    36
128260    36
128261    36
128262    36
128263    60
128264    36
128265    36
128266    36
128267    36
128268    60
128269    36
128270    36
128271    36
128272    36
128273    60
128274    36
128275    36
128276    36
128277    60
128278    36
128279    36
128280    36
128281    36
128282    36
128283    36
128284    36
128285    36
128286    36
128287    36
128288    36
128289    60
128290    36
128291    36
128292    36
128293    36
128294    36
128295    36
128296    36
128297    36
128298    36
128299    60
128300    36
128301    36
128302    60
128303    36
128304    36
128305    36
128306    60
128307    36
128308    36
128309    36
128310    36
128311    60
128312    36
128313    60
128314    36
128315    36
128316    36
128317    60
128318    36
128319    60
128320    60
128321    36
128322    36
128323    60
128324    60
128325    36
128326    36
128327    36
128328    36
128329    36
128330    60
128331    60
128332    36
128333    36
128334    36
128335    36
128336    36
128337    60
128338    36
128339    36
128340    36
128341    60
128342    36
128343    60
128344    36
128345    60
128346    36
128347    60
128348    36
128349    36
128350    36
128351    60
128352    36
128353    36
128354    36
128355    36
128356    36
128357    36
128358    36
128359    36
128360    60
128361    36
128362    60
128363    36
128364    36
128365    36
128366    36
128367    36
128368    36
128369    36
128370    36
128371    60
128372    36
128373    60
128374    60
128375    36
128376    36
128377    36
128378    60
128379    60
128380    60
128381    36
128382    60
128383    36
128384    36
128385    36
128386    36
128387    60
128388    36
128389    36
128390    36
128391    36
128392    36
128393    36
128394    36
128395    36
128396    60
128397    60
128398    60
128399    36
128400    60
128401    36
128402    60
128403    36
128404    60
128405    36
128406    36
128407    36
128408    36
128409    36
128410    36
128411    36
Name: term, Length: 128412, dtype: int64

In [37]:
# Create a new dataframe column loan_status_is_great. It should contain the 
# integer 1 if loan_status is "Current" or "Fully Paid." 
# Else it should contain the integer 0.

df['loan_status_is_great'] = [1 if x in ['Current','Fully Paid'] else 0 for x in df['loan_status']]




df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_is_great,last_pymnt_d_month,last_pymnt_d_year
0,10000,10000,10000.0,36,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8540.01,8540.01,1936.77,1936.77,1459.99,476.78,0.0,0.0,0.0,2019-07-01,324.23,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
1,4000,4000,4000.0,36,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3510.60,3510.60,926.28,926.28,489.40,436.88,0.0,0.0,0.0,2019-07-01,155.68,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
2,5000,5000,5000.0,36,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (16-30 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,2019-06-01,180.69,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0,6.0,2019.0
3,23000,23000,23000.0,60,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21597.84,21597.84,3686.64,3686.64,1402.16,2284.48,0.0,0.0,0.0,2019-07-01,620.81,Jul-2019,Jul-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
4,8000,8000,8000.0,36,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,7021.26,7021.26,1852.50,1852.50,978.74,873.76,0.0,0.0,0.0,2019-07-01,311.35,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0

In [0]:
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], 
                                        infer_datetime_format=True)
# Make last_pymnt_d_month column

df["last_pymnt_d_month"] = df["last_pymnt_d"].dt.month

In [0]:
# Make last_pymnt_d_year column.

df["last_pymnt_d_year"] = df["last_pymnt_d"].dt.year

In [27]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_is_great,last_pymnt_d_month,last_pymnt_d_year
0,10000,10000,10000.0,36,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8540.01,8540.01,1936.77,1936.77,1459.99,476.78,0.0,0.0,0.0,2019-07-01,324.23,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True,7.0,2019.0
1,4000,4000,4000.0,36,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3510.60,3510.60,926.28,926.28,489.40,436.88,0.0,0.0,0.0,2019-07-01,155.68,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True,7.0,2019.0
2,5000,5000,5000.0,36,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (16-30 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,2019-06-01,180.69,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,False,6.0,2019.0
3,23000,23000,23000.0,60,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21597.84,21597.84,3686.64,3686.64,1402.16,2284.48,0.0,0.0,0.0,2019-07-01,620.81,Jul-2019,Jul-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True,7.0,2019.0
4,8000,8000,8000.0,36,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,7021.26,7021.26,1852.50,1852.50,978.74,873.76,0.0,0.0,0.0,2019-07-01,311.35,Jul-2019,Jul-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True,7.0,2019.0

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01